version: '2'
services:
  postgres:
    container_name: dev_postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes_from:
      - pgdata

  pgdata:
    image: postgres
    volumes:
      - /Users/rafaeljesus/postgresql:/var/lib/postgresql/data

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd --broadcast-address=0.0.0.0
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=0.0.0.0
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"
